// ============================================================================
//  CRITTER QUEST — QUESTS
//  Multi-step story quests. Each is given by a person you meet by entering a
//  house. Step kinds:
//    math   — solve a math problem in the quest-giver's dialog
//    catch  — catch a named (wild) creature that appears while the step is active
//    item   — collect N glowing quest items that appear in a zone
//    goto   — travel to a special location that appears only during this step
//    boss   — reach the revealed location; a quest-only creature appears — catch it
//    riddle — answer a word riddle in the quest-giver's dialog
//    talk   — go find and talk to a specific townsperson (marked on the map)
//    guardian — reach the lair and fight the Guardian of Paradoxis (timed boss)
//  quest-only creatures (creatures.js `quest` field) and quest items only show
//  up while their quest step is active. Most steps also lean on math.
// ============================================================================

window.QUESTS = [
  {
    id: "q-emberheart", name: "The Emberheart Cinders", color: "#e8703a", icon: "🔥",
    house: { id: "house-ember", name: "Fira's Forge", tx: 50, ty: 4, deco: "house1" },
    giverName: "Old Fira", giverAv: { skin: 3, hair: 2, shirt: 3, pants: 1, hat: "none", glasses: "square" },
    intro: "Long ago the Emberheart Shrine kept all of Ember Ridge warm. Its flame has nearly gone out, and the ridge grows cold. Help me relight it, and its guardian will be yours!",
    steps: [
      { kind: "math", level: 1, text: "Warm up your wits — solve Fira's puzzle.", giverLine: "First, prove your mind is sharp. Solve this!" },
      { kind: "item", item: "ember-cinder", itemName: "Ember Cinder", emoji: "🔥", count: 3, zone: "ridge",
        text: "Gather 3 Ember Cinders glowing on Ember Ridge." },
      { kind: "goto", loc: "loc-emberheart", locName: "Emberheart Shrine", tx: 44, ty: 4, zone: "ridge",
        text: "Carry the Cinders to the Emberheart Shrine (now on your map)." },
      { kind: "boss", creature: "cindermane", loc: "loc-emberheart", tx: 44, ty: 4,
        text: "The shrine flares to life — the Cindermane appears! Catch it." },
    ],
    reward: { xp: 320, orbs: { ridge: 5, prism: 1 } },
    outro: "The ridge glows warm once more, and the Cindermane has chosen you. Ember Ridge thanks you!",
  },
  {
    id: "q-greenheart", name: "The Greenheart Hollow", color: "#5cb85c", icon: "🌿",
    house: { id: "house-grove", name: "Elowen's Cabin", tx: 6, ty: 22, deco: "house2" },
    giverName: "Warden Elowen", giverAv: { skin: 1, hair: 3, shirt: 2, pants: 2, hat: "ranger", glasses: "green" },
    intro: "The Whispering Woods hide a secret grove where the very first seed still sleeps. Prove yourself a friend to the forest and its sprite will reveal the way.",
    steps: [
      { kind: "math", level: 1, text: "Answer Elowen's riddle of numbers.", giverLine: "The forest tests all who enter. Solve this riddle." },
      { kind: "catch", creature: "mossling", zone: "forest", text: "Befriend a Mossling in the Whispering Woods." },
      { kind: "goto", loc: "loc-greenheart", locName: "Greenheart Hollow", tx: 6, ty: 30, zone: "forest",
        text: "Follow the mossy trail to the Greenheart Hollow (now on your map)." },
      { kind: "boss", creature: "gladewing", loc: "loc-greenheart", tx: 6, ty: 30,
        text: "The Gladewing flits from the hollow — catch it!" },
    ],
    reward: { xp: 340, orbs: { forest: 5, prism: 1 } },
    outro: "The Gladewing trusts you, and the first seed sleeps easy. The woods will remember your kindness.",
  },
  {
    id: "q-tidecaller", name: "Song of the Deep", color: "#4aa3df", icon: "🌊",
    house: { id: "house-lake", name: "Nerys's Boathouse", tx: 16, ty: 30, deco: "house1" },
    giverName: "Tidecaller Nerys", giverAv: { skin: 2, hair: 6, shirt: 5, pants: 0, hat: "none", glasses: "round" },
    intro: "At the bottom of Lake Lumen sleeps the Sablefin, keeper of the drowned stars. Only the old Tidecaller's Song can wake it — and only a clever mind can learn the Song.",
    steps: [
      { kind: "math", level: 2, text: "Learn the first notes of the Tidecaller's Song.", giverLine: "The Song is made of numbers. Learn its first measure." },
      { kind: "item", item: "moon-pearl", itemName: "Moon Pearl", emoji: "🌙", count: 3, zone: "lake",
        text: "Gather 3 Moon Pearls shining on the shores of Lake Lumen." },
      { kind: "goto", loc: "loc-tidecaller", locName: "Moonlit Cove", tx: 28, ty: 22, zone: "lake",
        text: "Bring the Pearls to the Moonlit Cove (now on your map)." },
      { kind: "boss", creature: "sablefin", loc: "loc-tidecaller", tx: 28, ty: 22,
        text: "The water spirals — the Sablefin rises from the deep. Catch it!" },
    ],
    reward: { xp: 360, orbs: { lake: 5, prism: 1 } },
    outro: "The Sablefin coils gently at your side. The drowned stars twinkle a little brighter tonight.",
  },
  {
    id: "q-sandsong", name: "The Singing Dunes", color: "#e6b52c", icon: "🏜️",
    house: { id: "house-desert", name: "Rashid's Tent", tx: 58, ty: 22, deco: "house2" },
    giverName: "Nomad Rashid", giverAv: { skin: 4, hair: 1, shirt: 3, pants: 3, hat: "none", glasses: "shades" },
    intro: "The dunes of Sundune hum with an ancient rhythm — the Sandsong. Beneath them sleeps the Dustmaw. Master the Sandsong's numbers and you may wake it without fear.",
    steps: [
      { kind: "math", level: 2, text: "Practice the Sandsong's rhythm (a puzzle).", giverLine: "The Sandsong is a rhythm of numbers. Keep the beat!" },
      { kind: "catch", creature: "duneling", zone: "desert", text: "Catch a Duneling to guide you across the sand." },
      { kind: "item", item: "sun-shard", itemName: "Sun Shard", emoji: "☀️", count: 3, zone: "desert",
        text: "Collect 3 Sun Shards buried in the Sundune Desert." },
      { kind: "boss", creature: "dustmaw", loc: "loc-sandsong", locName: "The Hollow Dune", tx: 64, ty: 20, zone: "desert",
        text: "Play the Sandsong at the Hollow Dune — the Dustmaw erupts! Catch it." },
    ],
    reward: { xp: 380, orbs: { desert: 5, prism: 1 } },
    outro: "The Dustmaw rumbles a contented note. The desert's song is yours to keep.",
  },
  {
    id: "q-starfall", name: "Chasing the Starfall", color: "#8f6ec9", icon: "✦",
    house: { id: "house-observatory", name: "Vega's Observatory", tx: 34, ty: 24, deco: "house1" },
    giverName: "Astronomer Vega", giverAv: { skin: 0, hair: 7, shirt: 4, pants: 0, hat: "none", glasses: "round" },
    intro: "Once a century, a star falls that is really the Glimmerhart coming home. Tonight is the night! Chart its path through the Astral Rift and follow it to where it lands.",
    steps: [
      { kind: "math", level: 2, text: "Chart the Glimmerhart's path (solve the star-map).", giverLine: "The stars move by numbers. Chart the Glimmerhart's path!" },
      { kind: "goto", loc: "portal-village", locName: "the Astral Portal", tx: 35, ty: 33, zone: "meadow",
        text: "Step through the ✦ Astral Portal near the village into the Rift." },
      { kind: "catch", creature: "nebulyn", zone: "rift", text: "Catch a Nebulyn drifting in the Astral Rift." },
      { kind: "item", item: "star-fragment", itemName: "Star Fragment", emoji: "⭐", count: 3, zone: "rift",
        text: "Gather 3 Star Fragments falling through the Rift." },
      { kind: "boss", creature: "glimmerhart", loc: "loc-starfall", locName: "the Starfall", tx: 80, ty: 30, zone: "rift",
        text: "Follow the Fragments to where the Starfall lands — the Glimmerhart! Catch it." },
    ],
    reward: { xp: 550, orbs: { rift: 4, prism: 2 } },
    outro: "The Glimmerhart lowers its glowing antlers and grants your smallest wish. You have caught a falling star.",
  },

  // ---- HARD / LONG QUESTS ----------------------------------------------
  {
    id: "q-frostcrown", name: "The Frostcrown Trials", color: "#5fa8de", icon: "❄️",
    house: { id: "house-frost", name: "Yuki's Lodge", tx: 8, ty: 4, deco: "house2" },
    giverName: "Elder Yuki", giverAv: { skin: 1, hair: 0, shirt: 5, pants: 1, hat: "beanie", glasses: "round" },
    intro: "Atop Frostpeak, the ancient Frost Warden Auravern sealed itself in the Frostcrown Spire, vowing to serve only a trainer who could pass its three Trials of mind and heart. Many have frozen trying. I have watched you, and I believe you are ready. But be warned — the Trials do not forgive a careless mind.",
    steps: [
      { kind: "math", level: 3, text: "First Trial: solve the Riddle of Ice.", giverLine: "The First Trial is of the mind. Solve the Riddle of Ice — and no guessing." },
      { kind: "item", item: "frost-sigil", itemName: "Frost Sigil", emoji: "❄️", count: 4, zone: "tundra",
        text: "Gather 4 Frost Sigils frozen into the Frostpeak drifts." },
      { kind: "catch", creature: "woolhorn", zone: "tundra", text: "Earn the trust of a Woolhorn to carry you through the blizzard." },
      { kind: "math", level: 3, text: "Second Trial: the Warden's Reckoning.", giverLine: "The Second Trial is harder still. Reckon this exactly." },
      { kind: "catch", creature: "glacimoth", zone: "tundra", text: "A Glacimoth lights the storm — catch it to find your way." },
      { kind: "item", item: "aurora-shard", itemName: "Aurora Shard", emoji: "🌌", count: 4, zone: "tundra",
        text: "Collect 4 Aurora Shards fallen from the northern lights." },
      { kind: "goto", loc: "loc-frostcrown", locName: "the Frostcrown Spire", tx: 4, ty: 3, zone: "tundra",
        text: "Climb to the Frostcrown Spire, now revealed on your map." },
      { kind: "boss", creature: "auravern", loc: "loc-frostcrown", tx: 4, ty: 3, zone: "tundra",
        text: "Third Trial: the Frost Warden Auravern awakens. Catch it — its crown of frost will resist you." },
    ],
    reward: { xp: 700, orbs: { tundra: 6, prism: 3 } },
    outro: "The Frostcrown Spire falls silent, and Auravern lowers its crowned head to you at last. Frostpeak has a new Warden's friend — and it is you.",
  },
  {
    id: "q-crystalcrown", name: "Heart of the Gleamcave", color: "#b06fe0", icon: "💎",
    house: { id: "house-cavern", name: "Garnet's Dig", tx: 66, ty: 44, deco: "house1" },
    giverName: "Prospector Garnet", giverAv: { skin: 3, hair: 2, shirt: 3, pants: 3, hat: "cap", glasses: "shades" },
    intro: "Deep under the Gleamcave sleeps Prismegis, the Crystal Sovereign, whose heartgem once lit every tunnel in the mountain. A cave-in stole its light and its slumber both, and the deep dark has crept back in. Help me forge the Gleamkey and wake the Sovereign — but the old locks answer only to sharp arithmetic.",
    steps: [
      { kind: "math", level: 3, text: "Garnet's assay: prove you can reckon carats.", giverLine: "No fool wakes a Sovereign. Assay this figure exactly." },
      { kind: "item", item: "raw-geode", itemName: "Raw Geode", emoji: "🪨", count: 4, zone: "cavern",
        text: "Pry 4 Raw Geodes from the walls of the Gleamcave." },
      { kind: "catch", creature: "glowbat", zone: "cavern", text: "Follow a Glowbat's light deeper into the dark." },
      { kind: "math", level: 3, text: "Cut the Gleamkey — a puzzle of exact angles.", giverLine: "One wrong cut ruins the key. Solve it precisely." },
      { kind: "catch", creature: "gleamkit", zone: "cavern", text: "A Gleamkit lights the sealed door — catch it to pass." },
      { kind: "item", item: "prism-facet", itemName: "Prism Facet", emoji: "💠", count: 4, zone: "cavern",
        text: "Gather 4 Prism Facets to complete the Gleamkey." },
      { kind: "goto", loc: "loc-crystalthrone", locName: "the Crystal Throne", tx: 70, ty: 49, zone: "cavern",
        text: "Carry the Gleamkey to the Crystal Throne, now on your map." },
      { kind: "boss", creature: "prismegis", loc: "loc-crystalthrone", tx: 70, ty: 49, zone: "cavern",
        text: "The Gleamkey turns — Prismegis wakes! Catch the Sovereign; its refractions will guard it." },
    ],
    reward: { xp: 720, orbs: { cavern: 6, prism: 3 } },
    outro: "Prismegis' heartgem blazes, and light floods every tunnel of the Gleamcave at once. The Crystal Sovereign walks at your side, and the mountain shines for you.",
  },

  // ---- INTRICATE MULTI-STEP QUESTS -------------------------------------
  {
    id: "q-tideglass", name: "The Tideglass Prophecy", color: "#1f8f8a", icon: "🔱",
    house: { id: "house-oracle", name: "Maris's Tidehut", tx: 14, ty: 24, deco: "house2" },
    giverName: "Oracle Maris", giverAv: { skin: 2, hair: 6, shirt: 5, pants: 0, hat: "none", glasses: "round" },
    intro: "Beneath Lake Lumen lies the Sunken Sanctum — a drowned temple whose song was never finished. The Tideglass Prophecy foretells a clever trainer who will complete it and wake the light that sleeps below. The tides have been whispering your name. Will you help me finish the song?",
    steps: [
      { kind: "talk", npc: "npc-angler", npcName: "Angler Moss",
        line: "The old tide-word? Aye, my gran taught me. It's the answer to the lake's own riddle — solve it, and the Sanctum will hear you. Off you go back to Maris now.",
        text: "Seek Angler Moss by the southern marsh and learn the old tide-word." },
      { kind: "riddle", prompt: "I have a bed but never sleep, a mouth but never eat, I run but never walk, and I always find the sea. What am I?",
        answers: ["river", "a river"], hint: "It flows down to the sea.",
        giverLine: "Now speak the tide-word Angler Moss sent you for. Answer the lake's riddle!",
        text: "Return to Oracle Maris and speak the tide-word (answer the lake's riddle)." },
      { kind: "math", level: 3, giverLine: "Good! The temple's first lock is a number. Solve it exactly.",
        text: "Solve Oracle Maris's tide-cipher." },
      { kind: "item", item: "tide-token", itemName: "Tide Token", emoji: "🔷", count: 3, zone: "lake",
        text: "Gather 3 Tide Tokens shining along the shores of Lake Lumen." },
      { kind: "goto", loc: "portal-sanctum", locName: "the Tidewhirl", tx: 23, ty: 31, zone: "lake",
        text: "Step into the 🌀 Tidewhirl on the lake's western shore to descend into the Sunken Sanctum." },
      { kind: "catch", creature: "gillfin", zone: "sanctum",
        text: "A Gillfin guards the temple's inner doors — catch it to pass." },
      { kind: "item", item: "sanctum-sigil", itemName: "Sanctum Sigil", emoji: "🔱", count: 4, zone: "sanctum",
        text: "Collect 4 Sanctum Sigils glowing in the drowned halls." },
      { kind: "goto", loc: "loc-tidealtar", locName: "the Tideglass Altar", tx: 98, ty: 42, zone: "sanctum",
        text: "Carry the Sigils to the Tideglass Altar, deep in the Sanctum." },
      { kind: "boss", creature: "abyssalux", loc: "loc-tidealtar", tx: 98, ty: 42, zone: "sanctum",
        text: "Sing the finished Prophecy — Abyssalux, the leviathan of light, wakes! Catch it (its radiance will guard it)." },
    ],
    reward: { xp: 750, orbs: { sanctum: 6, lake: 4, prism: 3 } },
    outro: "Light blazes through every drowned hall as Abyssalux rises and the Prophecy is fulfilled at last. Oracle Maris weeps for joy — the Sunken Sanctum sings again, whole, and you are the hero of the tides.",
  },
  {
    id: "q-clockwork", name: "The Clockwork Heart", color: "#c69a3c", icon: "⚙️",
    house: { id: "house-workshop", name: "Cog's Workshop", tx: 48, ty: 26, deco: "house1" },
    giverName: "Tinker Cog", giverAv: { skin: 3, hair: 5, shirt: 7, pants: 2, hat: "cap", glasses: "square" },
    intro: "In the age of gears, the great Aurumaton kept the very seasons turning true — until it wound down and its parts were scattered to the ends of the world. I have spent my whole life gathering the pieces. Help me find the last few, solve the locks that guard its heart, and together we'll wake the golden wonder!",
    steps: [
      { kind: "math", level: 3, giverLine: "First, prove you can keep time. A tinkerer lives or dies by arithmetic — solve this!",
        text: "Solve Tinker Cog's timing puzzle." },
      { kind: "item", item: "brass-gear", itemName: "Brass Gear", emoji: "⚙️", count: 3, zone: "ridge",
        text: "Salvage 3 Brass Gears from the old machines rusting on Ember Ridge." },
      { kind: "item", item: "copper-coil", itemName: "Copper Coil", emoji: "🔩", count: 3, zone: "cavern",
        text: "Mine 3 Copper Coils from deep in the Gleamcave Hollows." },
      { kind: "catch", creature: "cogsprite", zone: "meadow",
        text: "A living gear — a Cogsprite — ticks around Willowmere Meadow. Catch it; it belongs to the machine." },
      { kind: "talk", npc: "npc-miner", npcName: "Miner Quill",
        line: "This humming crystal? It's been ticking in my pocket for weeks and driving me batty. The automaton's core, you say? Here — take it, and welcome!",
        text: "Miner Quill dug up the automaton's humming core crystal — go collect it from him near the caverns." },
      { kind: "riddle", prompt: "The more of me you take, the more you leave behind. What am I?",
        answers: ["footsteps", "footprints", "steps"], hint: "You make them as you walk.",
        giverLine: "The heart's final lock is a riddle, not a number. Answer it and the core will open.",
        text: "Return to Tinker Cog and answer the heart's final riddle." },
      { kind: "item", item: "aether-spring", itemName: "Aether Spring", emoji: "✨", count: 3, zone: "sanctum",
        text: "The mainspring needs Aether, found only in the Sunken Sanctum (through the Tidewhirl on Lake Lumen). Gather 3." },
      { kind: "goto", loc: "loc-clockwork", locName: "the Clockwork Vault", tx: 50, ty: 30, zone: "meadow",
        text: "Bring every part to the Clockwork Vault beside the village." },
      { kind: "boss", creature: "aurumaton", loc: "loc-clockwork", tx: 50, ty: 30, zone: "meadow",
        text: "The parts lock together with a great golden tick — the Aurumaton wakes! Catch it (its clockwork will guard it)." },
    ],
    reward: { xp: 780, orbs: { ridge: 3, cavern: 3, sanctum: 3, prism: 3 } },
    outro: "With a deep golden tick the Aurumaton comes alive, and somewhere far off the seasons steady themselves on their turning. Tinker Cog dances a little jig of pure joy. You have rebuilt a true wonder of the old world.",
  },

  // ======================= THE EPIC QUEST (Paradoxis) ====================
  {
    id: "q-paradox", name: "The Key to Paradoxis", color: "#c026d3", icon: "⧉", epic: true,
    house: { id: "house-vex", name: "Vex's Study", tx: 44, ty: 30, deco: "house2" },
    giverName: "Professor Vex", giverAv: { skin: 1, hair: 7, shirt: 6, pants: 1, hat: "none", glasses: "square" },
    intro: "Reality is fraying, my friend. Impossible things — paradoxes — are leaking into our world from Paradoxis, a sealed realm of the truly absurd, guarded since the beginning of time by the Guardian of Paradoxis. To mend the fraying, someone must enter Paradoxis and set it right. But the Gate opens only for a mind that can hold a contradiction without breaking. Prove yours can, gather the leaking Paradox Shards, learn what you must, and I will send you to face the Guardian for the Orb of Entry. This will be the greatest trial you have faced. Are you ready?",
    steps: [
      { kind: "math", level: 3, giverLine: "First, prove your logic is sound. A mind that can't add can't hold a paradox. Solve this!",
        text: "Solve Professor Vex's opening proof." },
      { kind: "riddle", prompt: "The more you take away from me, the bigger I get. What am I?",
        answers: ["a hole", "hole", "holes"], hint: "You dig it, and it only grows.",
        giverLine: "Now a paradox of words. Answer carefully — this is the shape of the thing we face.",
        text: "Answer Professor Vex's first paradox riddle." },
      { kind: "talk", npc: "npc-baker", npcName: "Baker Tilly",
        line: "Ah, the Professor sent you? I've been baking a loaf that's never quite done — pull it out and it's raw, leave it and it's raw. A little paradox of my own! Here, take my notes on where the Shards are leaking. Off you go!",
        text: "Baker Tilly has been studying the leaks — go hear what she's found." },
      { kind: "item", item: "paradox-shard", itemName: "Paradox Shard", emoji: "🟪", count: 3, zone: "ridge",
        text: "Paradox Shards are leaking onto Ember Ridge — gather 3 before they fray it further." },
      { kind: "catch", creature: "windrake", zone: "meadow",
        text: "The frayed air has stirred up a Windrake over Willowmere — catch it to prove your reflexes." },
      { kind: "riddle", prompt: "I am always coming but never arrive; I am always ahead of you and never here. What am I?",
        answers: ["the future", "future", "tomorrow"], hint: "You walk toward it all your life.",
        giverLine: "The Guardian will test your certainty. Answer this — and be sure.",
        text: "Return to Professor Vex and answer the riddle of what never arrives." },
      { kind: "item", item: "paradox-shard", itemName: "Paradox Shard", emoji: "🟪", count: 3, zone: "sanctum",
        text: "The fraying has reached the Sunken Sanctum — gather 3 more Shards from the drowned halls." },
      { kind: "talk", npc: "npc-trader", npcName: "Trader Vish",
        line: "The Guardian, eh? I once traded for a coin that lands on neither side — spun it a hundred times, never heads, never tails. That's the Guardian's nature: it is and it isn't, all at once. Strike it true and quickly and it must yield. Now go — the Professor's waiting.",
        text: "Trader Vish once held an impossible coin — ask him about the Guardian's nature." },
      { kind: "math", level: 3, giverLine: "The Gate's first lock is a number that shouldn't resolve — but it does. Solve it exactly.",
        text: "Solve the Gate's first numeric lock with Professor Vex." },
      { kind: "item", item: "paradox-shard", itemName: "Paradox Shard", emoji: "🟪", count: 3, zone: "rift",
        text: "The last Shards have drifted into the Astral Rift — gather 3 to complete the Key." },
      { kind: "riddle", prompt: "You can give it to someone and still keep it for yourself. What is it?",
        answers: ["your word", "a promise", "promise", "word"], hint: "You give it, yet you never lose it.",
        giverLine: "The final lock. Give me the answer, and the Key to Paradoxis is complete.",
        text: "Answer Professor Vex's final riddle to finish the Key to Paradoxis." },
      { kind: "guardian", loc: "loc-guardian", locName: "the Guardian's Lair", tx: 50, ty: 46, zone: "marsh",
        text: "The Key is complete! Travel to the Guardian's Lair beside the sealed Gate (south of the village) and defeat the Guardian of Paradoxis for the Orb of Entry." },
    ],
    reward: { xp: 900, orbs: { paradoxis: 6, prism: 4 } },
    outro: "You did it — you faced the Guardian and won the Orb of Entry. The fraying is mending, and the Paradox Gate answers only to you now. Step through whenever you like: Paradoxis, and all its impossible creatures, are yours to explore. You are, truly, a hero of two worlds.",
  },

  // ============ SKYHAVEN REACH & EMBERDEEP CALDERA QUESTS ===============
  {
    id: "q-skysong", name: "The Song of Skyhaven", color: "#5aa9e6", icon: "🌬️",
    house: { id: "house-aerie", name: "Wren's Aerie", tx: 38, ty: 4, deco: "house2" },
    giverName: "Aeronaut Wren", giverAv: { skin: 0, hair: 3, shirt: 1, pants: 0, hat: "cap", glasses: "round" },
    intro: "High above Ember Ridge, past a rising column of warm air called the Windrise, float the islands of Skyhaven Reach. They stay up because Zephyrion, the Storm Sovereign, dreams beneath them — and lately its dreaming has grown restless. Learn the old Skysong with me, and we'll go up there and settle it before an island falls out of the sky.",
    steps: [
      { kind: "math", level: 2, giverLine: "The Skysong is counted, not just sung. Keep the measure — solve this.",
        text: "Learn the first measure of the Skysong with Aeronaut Wren." },
      { kind: "item", item: "wind-chime", itemName: "Wind Chime", emoji: "🎐", count: 3, zone: "ridge",
        text: "Gather 3 Wind Chimes from the high crags of Ember Ridge." },
      { kind: "goto", loc: "portal-sky", locName: "the Windrise", tx: 42, ty: 8, zone: "ridge",
        text: "Ride the 🌬️ Windrise up into Skyhaven Reach." },
      { kind: "catch", creature: "skimmet", zone: "sky",
        text: "Catch a Skimmet — its kitesong carries the Skysong's melody." },
      { kind: "riddle", prompt: "I have no voice, yet I make every tree in the forest speak. What am I?",
        answers: ["the wind", "wind"], hint: "You feel me but never see me.",
        giverLine: "Now the Skysong's asking-verse. Answer it, and Zephyrion will hear you.",
        text: "Return to Aeronaut Wren and answer the Skysong's asking-verse." },
      { kind: "item", item: "sky-feather", itemName: "Sky Feather", emoji: "🪶", count: 3, zone: "sky",
        text: "Collect 3 Sky Feathers drifting between the floating islands." },
      { kind: "boss", creature: "zephyrion", loc: "loc-skysong", locName: "the Highest Cloudbank", tx: 131, ty: 20, zone: "sky",
        text: "Sing the finished Skysong at the Highest Cloudbank — Zephyrion wakes! Catch it (its storm will guard it)." },
    ],
    reward: { xp: 640, orbs: { sky: 6, prism: 2 } },
    outro: "Zephyrion settles into a calm, contented sleep, and every island in the Reach steadies at once. Aeronaut Wren laughs and says the sky owes you one — and up here, that is worth a great deal.",
  },
  {
    id: "q-forgeheart", name: "Heart of the Emberdeep", color: "#e04a1e", icon: "🔨",
    house: { id: "house-forge", name: "Bellows's Forge", tx: 62, ty: 46, deco: "house1" },
    giverName: "Smith Bellows", giverAv: { skin: 5, hair: 1, shirt: 3, pants: 2, hat: "none", glasses: "shades" },
    intro: "Every hammer, nail and horseshoe in this world traces back to one forge — the Emberdeep Caldera, far below the Gleamcave, where Vulcanor the Forge Titan set down its hammer and slept. The old fires are guttering. Help me measure true, gather what's needed, and wake the first smith before the mountain goes cold forever.",
    steps: [
      { kind: "math", level: 2, giverLine: "A smith who can't measure is just a fellow hitting things. Measure this!",
        text: "Take Smith Bellows's measuring test." },
      { kind: "item", item: "ore-nugget", itemName: "Ore Nugget", emoji: "🪙", count: 3, zone: "cavern",
        text: "Mine 3 Ore Nuggets from the Gleamcave Hollows." },
      { kind: "goto", loc: "portal-caldera", locName: "the Magma Vent", tx: 68, ty: 42, zone: "cavern",
        text: "Slide down the 🌋 Magma Vent into the Emberdeep Caldera." },
      { kind: "catch", creature: "ashvane", zone: "caldera",
        text: "Befriend an Ashvane — the little forge sprites still keep the coals alive." },
      { kind: "item", item: "forge-coal", itemName: "Everburning Coal", emoji: "🔥", count: 4, zone: "caldera",
        text: "Gather 4 Everburning Coals to relight the great forge." },
      { kind: "riddle", prompt: "I am born in fire, shaped by blows, and the harder I am struck the stronger I become. What am I?",
        answers: ["steel", "iron", "a sword", "metal"], hint: "A smith makes me on an anvil.",
        giverLine: "One last thing — the smith's own riddle. Every apprentice must answer it.",
        text: "Answer Smith Bellows's apprentice riddle." },
      { kind: "boss", creature: "vulcanor", loc: "loc-forgeheart", locName: "the First Forge", tx: 147, ty: 20, zone: "caldera",
        text: "Strike the anvil at the First Forge — Vulcanor rises! Catch it (its furnace will guard it)." },
    ],
    reward: { xp: 660, orbs: { caldera: 6, prism: 2 } },
    outro: "Vulcanor lifts its hammer for the first time in an age, and every forge in the world flares bright at the same instant. Smith Bellows can't stop grinning. You have rekindled the first fire.",
  },
  {
    id: "q-stormchase", name: "The Storm That Never Ends", color: "#7b8ba0", icon: "🌩️",
    house: { id: "house-stormwatch", name: "Isolde's Stormwatch", tx: 28, ty: 6, deco: "house2" },
    giverName: "Stormwatcher Isolde", giverAv: { skin: 2, hair: 0, shirt: 5, pants: 1, hat: "beanie", glasses: "green" },
    intro: "There is a storm over Skyhaven that has rained without stopping for three hundred years. At its heart is Nimbaros, who cannot stop it any more than you could stop your own heartbeat — and who has been terribly, terribly lonely all that time. I don't want to fight it. I want to teach it how to rest. Will you help me?",
    steps: [
      { kind: "math", level: 3, giverLine: "Storms are arithmetic — pressure, distance, time. Work this one out exactly.",
        text: "Work out Isolde's storm-track calculation." },
      { kind: "talk", npc: "npc-scout", npcName: "Scout Bly",
        line: "The endless storm? Aye, I've watched it from the peak for years. It never moves and it never stops — but here's the odd thing: every night around midnight, it goes quiet for about a minute. Like it's sighing. Tell Isolde that.",
        text: "Scout Bly watches the sky from Frostpeak — ask what they've seen of the endless storm." },
      { kind: "item", item: "still-water", itemName: "Vial of Still Water", emoji: "💧", count: 3, zone: "tundra",
        text: "Collect 3 Vials of Still Water from the frozen Frostpeak lakes — water that has forgotten how to move." },
      { kind: "catch", creature: "cirrix", zone: "sky",
        text: "Catch a Cirrix in Skyhaven — the high serpents know where the storm's eye lies." },
      { kind: "riddle", prompt: "I fall but never break, and I break but never fall. What are we?",
        answers: ["night and day", "day and night", "nightfall and daybreak", "night day"],
        hint: "One of us falls in the evening; the other breaks in the morning.",
        giverLine: "Nimbaros only listens to those who can hold two things at once. Answer this.",
        text: "Return to Isolde and answer the riddle of what falls and what breaks." },
      { kind: "boss", creature: "nimbaros", loc: "loc-stormeye", locName: "the Eye of the Storm", tx: 125, ty: 42, zone: "sky",
        text: "Walk into the Eye of the Storm and meet Nimbaros. Catch it — and give it a friend at last." },
    ],
    reward: { xp: 620, orbs: { sky: 4, tundra: 3, prism: 2 } },
    outro: "For the first time in three centuries the rain stops. Nimbaros blinks at the sudden quiet, then at you, and the storm folds up like a blanket. Isolde is crying, a bit, and says these are the good kind of tears.",
  },
  {
    id: "q-lostlantern", name: "The Lost Lantern", color: "#f2d16b", icon: "🏮",
    house: { id: "house-lantern", name: "The Lampwright's Hut", tx: 32, ty: 44, deco: "house1" },
    giverName: "Lampwright Odell", giverAv: { skin: 3, hair: 5, shirt: 6, pants: 3, hat: "none", glasses: "square" },
    intro: "Sixty years ago my grandmother set her lantern down in Glowfen Marsh to help a lost traveller, and never found it again. But folk still see a light out there on the worst nights, leading people safely home. That's her lantern, still doing its job — a Lumenwick now. I'd very much like to bring it home. Would you help an old man do that?",
    steps: [
      { kind: "math", level: 1, giverLine: "First help me work out how much lamp oil we'll need. Careful now!",
        text: "Help Lampwright Odell work out the lamp oil." },
      { kind: "talk", npc: "npc-ranger", npcName: "Ranger Fenn",
        line: "The marsh light? I've followed it twice and both times it led me straight out of the bog and never asked a thing in return. Tell Odell it always heads north when it's done — like it's trying to go somewhere.",
        text: "Ranger Fenn has followed the marsh light before — go ask what they know." },
      { kind: "item", item: "glow-oil", itemName: "Flask of Glow Oil", emoji: "🪔", count: 3, zone: "marsh",
        text: "Gather 3 Flasks of Glow Oil from the marsh — a lantern that's walked for sixty years will be thirsty." },
      { kind: "riddle", prompt: "The more of me there is, the less you see. What am I?",
        answers: ["darkness", "dark", "the dark", "night"], hint: "A lantern is made to fight me.",
        giverLine: "Grandmother always said a lampwright must know their enemy. Name it for me.",
        text: "Answer Odell's lampwright riddle." },
      { kind: "boss", creature: "lumenwick", loc: "loc-lanternhome", locName: "the Old Crossing", tx: 36, ty: 48, zone: "marsh",
        text: "Set the fresh oil at the Old Crossing and wait — the Lumenwick comes. Catch it gently and bring it home." },
    ],
    reward: { xp: 480, orbs: { marsh: 5, prism: 2 } },
    outro: "The Lumenwick sits on Odell's windowsill, burning steady and bright, exactly where his grandmother's lantern used to sit. It has been looking for this spot for sixty years. Odell doesn't say anything for a while, and then he says thank you, twice.",
  },
  {
    id: "q-menagerie", name: "The Wandering Menagerie", color: "#7fc24a", icon: "🎪",
    house: { id: "house-menagerie", name: "Pip's Big Tent", tx: 46, ty: 20, deco: "house2" },
    giverName: "Ringmaster Pip", giverAv: { skin: 4, hair: 6, shirt: 0, pants: 0, hat: "flower", glasses: "round" },
    intro: "My travelling menagerie lost its star attraction years ago — a Chimerakit, a marvellous patchwork creature that is a bit of everything. It ran off to make friends in every region of the world, and honestly? Good for it. But I'd love to see it once more. It only shows itself to a trainer who has befriended creatures from all over. Shall we go find it together?",
    steps: [
      { kind: "math", level: 2, giverLine: "Every ringmaster can count a crowd in a blink. Your turn — how many?",
        text: "Count the crowd for Ringmaster Pip." },
      { kind: "catch", creature: "craghopper", zone: "ridge",
        text: "Befriend a Craghopper on Ember Ridge — a friend from the mountains." },
      { kind: "catch", creature: "sporelet", zone: "marsh",
        text: "Befriend a Sporelet in Glowfen Marsh — a friend from the wetlands." },
      { kind: "catch", creature: "nimbik", zone: "sky",
        text: "Befriend a Nimbik in Skyhaven Reach — a friend from the clouds." },
      { kind: "item", item: "friendship-token", itemName: "Friendship Token", emoji: "🎟️", count: 3, zone: "meadow",
        text: "Gather 3 Friendship Tokens around Willowmere — the Menagerie's old calling cards." },
      { kind: "talk", npc: "npc-nomad", npcName: "Nomad Zia",
        line: "The patchwork cub? Ha! It shared my campfire last spring, then trotted off east with a Duneling in tow. It collects friends the way I collect stories. Tell Pip it looked very happy.",
        text: "Nomad Zia travels everywhere — ask if they've crossed paths with the Chimerakit." },
      { kind: "riddle", prompt: "The more you give me away, the more of me you have. What am I?",
        answers: ["friendship", "love", "a friend", "friends", "kindness"], hint: "It is what this whole quest is about.",
        giverLine: "One last riddle — and it's the only one that matters, really.",
        text: "Answer Ringmaster Pip's final riddle." },
      { kind: "boss", creature: "chimerakit", loc: "loc-menagerie", locName: "the Old Show Field", tx: 42, ty: 22, zone: "meadow",
        text: "Wait at the Old Show Field — the Chimerakit comes bounding back! Catch it." },
    ],
    reward: { xp: 700, orbs: { meadow: 4, ridge: 3, marsh: 3, sky: 3, prism: 2 } },
    outro: "The Chimerakit barrels into Ringmaster Pip's arms, then immediately runs over to sniff every creature you own. Pip laughs until they cry. The Wandering Menagerie has its star back — though these days it mostly just wanders where it likes.",
  },

  // =============== HOME-REGION QUESTS (fourth wave) =====================
  {
    id: "q-frostfable", name: "The Frostpeak Fable", color: "#7fc4e0", icon: "📖",
    house: { id: "house-fable", name: "Vela's Story-Lodge", tx: 12, ty: 6, deco: "house1" },
    giverName: "Storyteller Vela", giverAv: { skin: 2, hair: 3, shirt: 4, pants: 1, hat: "beanie", glasses: "round" },
    intro: "Every fable we tell on long winter nights came from one creature: the Fablewyrm, who has been collecting stories since before there were people to tell them to. It sleeps coiled around the oldest tale of all — and it will only share that one with someone who brings it a story it has never heard. Help me find one, and we'll go wake it together.",
    steps: [
      { kind: "math", level: 2, giverLine: "A story needs shape — beats, pauses, a count. Work out this one's measure.",
        text: "Work out the measure of Vela's tale." },
      { kind: "catch", creature: "frostling", zone: "tundra",
        text: "Befriend a Frostling — every good winter story starts with one of these." },
      { kind: "talk", npc: "npc-icewright", npcName: "Icewright Thora",
        line: "A story nobody's heard? Here's one: I once carved a lantern out of clear ice and it burned for a whole winter without melting. Never told a soul, because nobody would believe me. You tell the Fablewyrm — it'll know I'm not lying.",
        text: "Icewright Thora keeps a story she's never told anyone — go and ask for it." },
      { kind: "item", item: "frost-page", itemName: "Frostbound Page", emoji: "📄", count: 3, zone: "tundra",
        text: "Gather 3 Frostbound Pages scattered across the drifts — pieces of tales the wind tore loose." },
      { kind: "riddle", prompt: "I am told but never spoken, read but never written by the one who reads me. What am I?",
        answers: ["a story", "story", "a tale", "tale", "stories"], hint: "You are inside one right now.",
        giverLine: "The Fablewyrm always asks this first. Answer it and it will listen to the rest.",
        text: "Return to Vela and answer the Fablewyrm's opening question." },
      { kind: "boss", creature: "fablewyrm", loc: "loc-fable", locName: "the Oldest Tale", tx: 6, ty: 6, zone: "tundra",
        text: "Tell Thora's story at the Oldest Tale — the Fablewyrm uncoils to listen. Catch it (its verse will guard it)." },
    ],
    reward: { xp: 600, orbs: { tundra: 6, prism: 2 } },
    outro: "The Fablewyrm listens to Thora's ice-lantern story all the way to the end, and then — for the first time in an age — tells one back. Vela writes it down with shaking hands. Frostpeak has a new fable tonight, and you are in it.",
  },
  {
    id: "q-deepecho", name: "The Deep Echo", color: "#a678c9", icon: "🔊",
    house: { id: "house-echo", name: "Bram's Listening Post", tx: 68, ty: 38, deco: "house2" },
    giverName: "Echo-listener Bram", giverAv: { skin: 4, hair: 2, shirt: 7, pants: 2, hat: "cap", glasses: "none" },
    intro: "Shout into the Gleamcave and something answers — but it isn't your voice coming back. It's Resonyx, the Echo Sovereign, who has been holding every sound ever made down here and repeating them a little better than we managed. Lately the echoes have gone wrong: they come back sad. I'd like to know why. Come listening with me.",
    steps: [
      { kind: "math", level: 2, giverLine: "Sound is distance and time. If you can't do that arithmetic you can't read an echo. Try it.",
        text: "Time an echo with Echo-listener Bram." },
      { kind: "item", item: "echo-shard", itemName: "Echo Shard", emoji: "🔷", count: 3, zone: "cavern",
        text: "Collect 3 Echo Shards — crystals that have caught a sound and kept it." },
      { kind: "catch", creature: "umbrite", zone: "cavern",
        text: "Catch an Umbrite; the dark inside it swallows noise, and we need one quiet thing." },
      { kind: "catch", creature: "quartzling", zone: "cavern",
        text: "Catch a Quartzling too — the polished walls they leave behind carry sound the furthest." },
      { kind: "riddle", prompt: "I speak without a mouth and hear without ears. I have nobody, but I come alive with the wind. What am I?",
        answers: ["an echo", "echo", "echoes"], hint: "It is the whole point of this quest.",
        giverLine: "Resonyx opens with a riddle about itself. It's rather proud of it. Go on.",
        text: "Return to Bram and answer Resonyx's riddle." },
      { kind: "boss", creature: "resonyx", loc: "loc-echo", locName: "the Sounding Chamber", tx: 70, ty: 50, zone: "cavern",
        text: "Call out once in the Sounding Chamber — Resonyx answers in person. Catch it (its chorus will guard it)." },
    ],
    reward: { xp: 620, orbs: { cavern: 6, prism: 2 } },
    outro: "It turns out Resonyx had simply gone a very long time without anyone new to talk to. Now the Gleamcave echoes come back cheerful again, and sometimes — Bram swears — with a joke attached.",
  },
  {
    id: "q-riftwalker", name: "The Riftwalker's Trail", color: "#5b6ee0", icon: "✦",
    house: { id: "house-riftcamp", name: "Sable's Riftcamp", tx: 30, ty: 28, deco: "house2" },
    giverName: "Riftwalker Sable", giverAv: { skin: 1, hair: 7, shirt: 0, pants: 0, hat: "none", glasses: "shades" },
    intro: "I've walked the Astral Rift more times than anyone alive, and lately the seams are wearing thin — little tears where the stars leak through. There's a Warden in there, Aetherion, who mends them, and it has been mending alone for a very long time. Let's go find it and lend a hand before the sky springs a proper leak.",
    steps: [
      { kind: "math", level: 3, giverLine: "Rift-walking is dead reckoning — no landmarks, only numbers. Reckon this exactly.",
        text: "Chart a rift-walker's bearing with Sable." },
      { kind: "goto", loc: "portal-village", locName: "the Astral Portal", tx: 35, ty: 33, zone: "meadow",
        text: "Step through the ✦ Astral Portal by the village into the Astral Rift." },
      { kind: "catch", creature: "starmote", zone: "rift",
        text: "Catch a Starmote — the little ones always drift toward a fresh tear." },
      { kind: "item", item: "seam-thread", itemName: "Seam Thread", emoji: "🧵", count: 4, zone: "rift",
        text: "Gather 4 Seam Threads — strands of starlight pulled loose from the sky's stitching." },
      { kind: "catch", creature: "quasarix", zone: "rift",
        text: "Catch a Quasarix; nothing else in the Rift burns bright enough to work by." },
      { kind: "riddle", prompt: "Mend me and I vanish; leave me and I grow. What am I?",
        answers: ["a hole", "hole", "a tear", "tear", "a rip", "rip", "holes"], hint: "It is exactly what Aetherion spends its days on.",
        giverLine: "The Warden asks this of everyone who offers to help. Answer honestly.",
        text: "Return to Sable and answer the Warden's question." },
      { kind: "boss", creature: "aetherion", loc: "loc-riftheart", locName: "the Thinnest Seam", tx: 82, ty: 16, zone: "rift",
        text: "Bring the Threads to the Thinnest Seam — Aetherion turns to look at you. Catch it (its starlight will guard it)." },
    ],
    reward: { xp: 680, orbs: { rift: 6, prism: 3 } },
    outro: "Aetherion stitches the last seam closed, then rests a wing on your shoulder — the first help it has accepted in a thousand years. Sable says the Rift hasn't looked this whole since they started walking it.",
  },
  {
    id: "q-marshlight", name: "The Marshlight Masquerade", color: "#6f9a4a", icon: "🎭",
    house: { id: "house-mask", name: "The Mask-maker's Shack", tx: 38, ty: 45, deco: "house1" },
    giverName: "Mask-maker Wren-Ellis", giverAv: { skin: 3, hair: 6, shirt: 6, pants: 0, hat: "flower", glasses: "none" },
    intro: "Once a year every light in Glowfen Marsh gathers for a masquerade, and Mirevail the Masked Marshlord presides over it in a face nobody has ever seen twice. This year I've been asked to make the guest of honour's mask — and I need a partner with steady hands and a good head for numbers. Fancy a night at the marsh ball?",
    steps: [
      { kind: "math", level: 2, giverLine: "A mask is measurements before it's magic. Get this wrong and it won't fit anybody.",
        text: "Measure the mask with Wren-Ellis." },
      { kind: "item", item: "marsh-silk", itemName: "Marsh Silk", emoji: "🧶", count: 3, zone: "marsh",
        text: "Gather 3 lengths of Marsh Silk from the glowfen spiders — the finest thread there is." },
      { kind: "catch", creature: "reedling", zone: "marsh",
        text: "Catch a Reedling; the ball needs a piper and they are the best in the fen." },
      { kind: "talk", npc: "npc-fenwarden", npcName: "Fen-warden Cobb",
        line: "The masquerade? Aye, I keep the invitations. Rule one: you must arrive wearing a face that isn't yours. Rule two — and this is the one folk forget — you must say thank you before you leave. Mirevail keeps score, you know.",
        text: "Fen-warden Cobb keeps the masquerade's rules — go and learn them before you attend." },
      { kind: "catch", creature: "peatpaw", zone: "marsh",
        text: "Catch a Peatpaw — nobody knows the hidden paths to the ball better." },
      { kind: "riddle", prompt: "I cover a face but show what you truly are. Wear me and everyone knows you less, and better. What am I?",
        answers: ["a mask", "mask", "masks"], hint: "You are making one right now.",
        giverLine: "Cobb's rule one, in riddle form. Mirevail will ask it at the door.",
        text: "Answer the doorway riddle for Wren-Ellis." },
      { kind: "boss", creature: "mirevail", loc: "loc-mask", locName: "the Masquerade Ring", tx: 28, ty: 49, zone: "marsh",
        text: "Present the finished mask at the Masquerade Ring — Mirevail steps out to dance. Catch it (its hundred masks will guard it)." },
    ],
    reward: { xp: 640, orbs: { marsh: 6, prism: 2 } },
    outro: "Mirevail wears your mask for the last dance of the night, and when it lifts the edge to say goodbye there is — just for a second — an ordinary, delighted face underneath. You remembered to say thank you. Wren-Ellis says that is why you were invited at all.",
  },

  // ================= THE SCALES OF AEQUOR (algebra epic) ================
  //  A long teaching quest. Each tier of the Great Scale introduces one new
  //  idea about solving multi-step equations: it is TAUGHT (lesson / a
  //  townsperson working an example), then PRACTISED by finishing a piece of
  //  written working (fillstep), then TESTED by catching the creature that
  //  embodies it. The boss asks for all of it at once.
  {
    id: "q-scales", name: "The Scales of Aequor", color: "#c9a227", icon: "⚖️", epic: true,
    house: { id: "house-balance", name: "The Balance House", tx: 22, ty: 36, deco: "house1" },
    giverName: "Keeper Aequa", giverAv: { skin: 2, hair: 1, shirt: 4, pants: 1, hat: "none", glasses: "round" },
    intro: "The Great Scale of Aequor has weighed every question ever asked, and it has begun to tilt. Its Keeper, Aequoron, will only right it for someone who understands what a scale really is — that the two sides must always stay equal, no matter what you do to them. That is the whole secret of solving for x. Stay with me and I'll teach you the five tiers, one at a time. It is a long road, but you will finish it knowing something rather wonderful.",
    steps: [
      // ---- TIER I: two-step equations ----
      { kind: "lesson", algebra: "two-step",
        giverLine: "Tier one. An equation is a scale: the = is the pivot. To get x on its own you undo what was done to it — and you undo it in reverse order, like taking off your boots before your socks. Watch.",
        text: "Tier I — learn to solve a two-step equation with Keeper Aequa." },
      { kind: "fillstep", algebra: "two-step", blanks: 2,
        giverLine: "Now write it out yourself. I've left gaps — choose the move, and give me the number it leaves behind.",
        text: "Tier I — fill in the missing steps of a two-step solution." },
      { kind: "catch", creature: "balanx", zone: "meadow",
        text: "Tier I — a Balanx has appeared in the meadow. Solve its equation to befriend it." },

      // ---- TIER II: combining like terms ----
      { kind: "talk", npc: "npc-mayor", npcName: "Mayor Pom", teach: "like-terms",
        line: "Aequa sent you? Ha! Here's how I count votes: I don't add a 'yes' to a 'no' — I put all the yeses in one pile first. Same with x's. Four x and three x are just seven x. Tidy up before you do anything else.",
        line2: "Gather the matching terms, then carry on exactly as you did in tier one. Off you go!",
        text: "Tier II — Mayor Pom counts votes in piles. Go and hear how it applies to x." },
      { kind: "lesson", algebra: "like-terms",
        giverLine: "Pom is right, of course. Before you undo anything, gather the x-terms into one. Then it's a two-step equation again — which you already know how to finish.",
        text: "Tier II — learn to combine like terms with Keeper Aequa." },
      { kind: "fillstep", algebra: "like-terms", blanks: 2,
        giverLine: "Your turn. Remember: gather first, then undo in reverse order.",
        text: "Tier II — fill in the missing steps of a combining-like-terms solution." },
      { kind: "catch", creature: "tallyx", zone: "forest",
        text: "Tier II — a Tallyx is gathering acorns in the Whispering Woods. Solve its equation to befriend it." },
      { kind: "item", item: "scale-weight", itemName: "Balance Weight", emoji: "⚖️", count: 3, zone: "meadow",
        text: "Tier II — gather 3 Balance Weights around Willowmere; the Great Scale will need them." },

      // ---- TIER III: variables on both sides ----
      { kind: "talk", npc: "npc-scribe", npcName: "Scribe Tessel", teach: "both-sides",
        line: "x on BOTH sides? Don't panic. Take the smaller pile of x's away from both sides at once — the scale stays level, and suddenly there's only x on the left. Then it's an ordinary tier-one problem again.",
        line2: "Every hard equation is just an easy one wearing a disguise. Peel the disguise off.",
        text: "Tier III — Scribe Tessel knows what to do when x appears twice. Go and ask." },
      { kind: "lesson", algebra: "both-sides",
        giverLine: "Tier three, and the trick Tessel gave you: subtract the smaller x-term from both sides. All the x's end up together, and the scale never tilts.",
        text: "Tier III — learn to handle variables on both sides with Keeper Aequa." },
      { kind: "fillstep", algebra: "both-sides", blanks: 2,
        giverLine: "Show me. Move the x's first, then the number, then divide.",
        text: "Tier III — fill in the missing steps of a variables-on-both-sides solution." },
      { kind: "catch", creature: "mirrolyn", zone: "lake",
        text: "Tier III — a Mirrolyn stands on both shores of Lake Lumen. Solve its equation to befriend it." },

      // ---- TIER IV: the distributive property ----
      { kind: "talk", npc: "npc-weigher", npcName: "Weigh-master Ballas", teach: "distribute",
        line: "Brackets! Look — if I've three crates and each holds an x and a 4, I don't have 'three crates', I have 3x and 12. The number outside gets shared with EVERYTHING inside. Not just the first thing. Everything.",
        line2: "Share it out fairly, then you're back on familiar ground.",
        text: "Tier IV — Weigh-master Ballas can explain brackets. Go and see him." },
      { kind: "lesson", algebra: "distribute",
        giverLine: "Tier four. The number outside the brackets multiplies every term inside — that's all 'distributing' means. Share it out, then solve as before.",
        text: "Tier IV — learn the distributive property with Keeper Aequa." },
      { kind: "fillstep", algebra: "distribute", blanks: 2,
        giverLine: "Distribute first. Then undo, in reverse order, as always.",
        text: "Tier IV — fill in the missing steps of a distributive solution." },
      { kind: "catch", creature: "sharewing", zone: "ridge",
        text: "Tier IV — a Sharewing is handing out shares on Ember Ridge. Solve its equation to befriend it." },

      // ---- TIER V: the full multi-step ----
      { kind: "lesson", algebra: "multi",
        giverLine: "The fifth and last tier, and it is only the other four stacked together: distribute, gather the x's onto one side, then undo in reverse order. Nothing new — just all of it at once.",
        text: "Tier V — learn the full multi-step method with Keeper Aequa." },
      { kind: "fillstep", algebra: "multi", blanks: 3,
        giverLine: "This is the master working. Four lines, three gaps. Take your time — I have every confidence.",
        text: "Tier V — complete the master working (three missing steps)." },
      { kind: "item", item: "true-token", itemName: "Token of True Measure", emoji: "🪙", count: 3, zone: "meadow",
        text: "Tier V — collect 3 Tokens of True Measure; Aequoron accepts no other payment." },
      { kind: "goto", loc: "loc-greatscale", locName: "the Great Scale", tx: 24, ty: 40, zone: "meadow",
        text: "Carry the Weights and Tokens to the Great Scale, west of the village." },
      { kind: "boss", creature: "aequoron", loc: "loc-greatscale", tx: 24, ty: 40, zone: "meadow",
        text: "Aequoron rises to weigh you. Solve its full multi-step equations to befriend it (its Scale will guard it)." },
    ],
    reward: { xp: 1000, orbs: { meadow: 6, prism: 4 } },
    outro: "Aequoron sets the Great Scale level with one finger and it stays there, perfectly balanced, for the first time in years. \"You did not memorise,\" Keeper Aequa says, sounding rather pleased. \"You understood. There is a great deal of difference, and the Scale can tell.\" You can solve for x now — properly, any equation they care to throw at you. That is the real reward, and Aequoron knew it all along.",
  },
];

window.QUEST_BY_ID = {};
window.QUESTS.forEach(function (q) { window.QUEST_BY_ID[q.id] = q; });
