// ============================================================================
//  CRITTER QUEST — QUESTS
//  Multi-step story quests. Each is given by a person you meet by entering a
//  house. Step kinds:
//    math     — solve a math problem in the quest-giver's dialog
//    catch    — catch a named (wild) creature that appears while the step is
//               active; `challenge: "bee"` (+ `pool`) or {algebra: type} makes
//               its encounter ask only that kind of question
//    item     — collect N glowing quest items that appear in a zone
//    goto     — travel to a special location that appears only during this step
//    boss     — reach the revealed location; a quest-only creature appears — catch it
//    riddle   — answer a word riddle in the quest-giver's dialog
//    talk     — go find and talk to a specific townsperson (marked on the map);
//               `teach: type` makes them work an algebra example for you
//    guardian — reach the lair and fight the Guardian of Paradoxis (timed boss)
//    lesson   — the giver works an algebra example, then you solve one
//    fillstep — fill in the missing moves of a worked algebra solution
//    drill    — solve `count` algebra problems in a row (one type or a list)
//    spellbee — spell words from the Spelling Bee list. `pool` is a slice of
//               the list as fractions ([0, 0.25] = first quarter); `count`
//               defaults to every word in the slice (all quests use 15);
//               words not yet asked in this quest come first; `mode` is copy, flash,
//               gaps, scramble or mix. A missed word comes back a few later.
//  quest-only creatures (creatures.js `quest` field) and quest items only show
//  up while their quest step is active.
//
//  RETIRED quests (`retired: true`) were all finished by our player, so their
//  stories were removed to keep the game light. Their houses stay on the map
//  and show the quest as Completed. (Full text is in git history.)
// ============================================================================

window.QUESTS = [
  // ============================ COMPLETED ===============================
  { id: "q-emberheart", name: "The Emberheart Cinders", color: "#e8703a", icon: "🔥", retired: true,
    house: { id: "house-ember", name: "Fira's Forge", tx: 50, ty: 4, deco: "house1" },
    giverName: "Old Fira", giverAv: { skin: 3, hair: 2, shirt: 3, pants: 1, hat: "none", glasses: "square" } },
  { id: "q-greenheart", name: "The Greenheart Hollow", color: "#5cb85c", icon: "🌿", retired: true,
    house: { id: "house-grove", name: "Elowen's Cabin", tx: 6, ty: 22, deco: "house2" },
    giverName: "Warden Elowen", giverAv: { skin: 1, hair: 3, shirt: 2, pants: 2, hat: "ranger", glasses: "green" } },
  { id: "q-tidecaller", name: "Song of the Deep", color: "#4aa3df", icon: "🌊", retired: true,
    house: { id: "house-lake", name: "Nerys's Boathouse", tx: 16, ty: 30, deco: "house1" },
    giverName: "Tidecaller Nerys", giverAv: { skin: 2, hair: 6, shirt: 5, pants: 0, hat: "none", glasses: "round" } },
  { id: "q-sandsong", name: "The Singing Dunes", color: "#e6b52c", icon: "🏜️", retired: true,
    house: { id: "house-desert", name: "Rashid's Tent", tx: 58, ty: 22, deco: "house2" },
    giverName: "Nomad Rashid", giverAv: { skin: 4, hair: 1, shirt: 3, pants: 3, hat: "none", glasses: "shades" } },
  { id: "q-starfall", name: "Chasing the Starfall", color: "#8f6ec9", icon: "✦", retired: true,
    house: { id: "house-observatory", name: "Vega's Observatory", tx: 34, ty: 24, deco: "house1" },
    giverName: "Astronomer Vega", giverAv: { skin: 0, hair: 7, shirt: 4, pants: 0, hat: "none", glasses: "round" } },
  { id: "q-frostcrown", name: "The Frostcrown Trials", color: "#5fa8de", icon: "❄️", retired: true,
    house: { id: "house-frost", name: "Yuki's Lodge", tx: 8, ty: 4, deco: "house2" },
    giverName: "Elder Yuki", giverAv: { skin: 1, hair: 0, shirt: 5, pants: 1, hat: "beanie", glasses: "round" } },
  { id: "q-crystalcrown", name: "Heart of the Gleamcave", color: "#b06fe0", icon: "💎", retired: true,
    house: { id: "house-cavern", name: "Garnet's Dig", tx: 66, ty: 44, deco: "house1" },
    giverName: "Prospector Garnet", giverAv: { skin: 3, hair: 2, shirt: 3, pants: 3, hat: "cap", glasses: "shades" } },
  { id: "q-tideglass", name: "The Tideglass Prophecy", color: "#1f8f8a", icon: "🔱", retired: true,
    house: { id: "house-oracle", name: "Maris's Tidehut", tx: 14, ty: 24, deco: "house2" },
    giverName: "Oracle Maris", giverAv: { skin: 2, hair: 6, shirt: 5, pants: 0, hat: "none", glasses: "round" } },
  { id: "q-clockwork", name: "The Clockwork Heart", color: "#c69a3c", icon: "⚙️", retired: true,
    house: { id: "house-workshop", name: "Cog's Workshop", tx: 48, ty: 26, deco: "house1" },
    giverName: "Tinker Cog", giverAv: { skin: 3, hair: 5, shirt: 7, pants: 2, hat: "cap", glasses: "square" } },
  { id: "q-paradox", name: "The Key to Paradoxis", color: "#c026d3", icon: "⧉", retired: true,
    house: { id: "house-vex", name: "Vex's Study", tx: 44, ty: 30, deco: "house2" },
    giverName: "Professor Vex", giverAv: { skin: 1, hair: 7, shirt: 6, pants: 1, hat: "none", glasses: "square" } },
  { id: "q-skysong", name: "The Song of Skyhaven", color: "#5aa9e6", icon: "🌬️", retired: true,
    house: { id: "house-aerie", name: "Wren's Aerie", tx: 38, ty: 4, deco: "house2" },
    giverName: "Aeronaut Wren", giverAv: { skin: 0, hair: 3, shirt: 1, pants: 0, hat: "cap", glasses: "round" } },
  { id: "q-forgeheart", name: "Heart of the Emberdeep", color: "#e04a1e", icon: "🔨", retired: true,
    house: { id: "house-forge", name: "Bellows's Forge", tx: 62, ty: 46, deco: "house1" },
    giverName: "Smith Bellows", giverAv: { skin: 5, hair: 1, shirt: 3, pants: 2, hat: "none", glasses: "shades" } },
  { id: "q-stormchase", name: "The Storm That Never Ends", color: "#7b8ba0", icon: "🌩️", retired: true,
    house: { id: "house-stormwatch", name: "Isolde's Stormwatch", tx: 28, ty: 6, deco: "house2" },
    giverName: "Stormwatcher Isolde", giverAv: { skin: 2, hair: 0, shirt: 5, pants: 1, hat: "beanie", glasses: "green" } },
  { id: "q-lostlantern", name: "The Lost Lantern", color: "#f2d16b", icon: "🏮", retired: true,
    house: { id: "house-lantern", name: "The Lampwright's Hut", tx: 32, ty: 44, deco: "house1" },
    giverName: "Lampwright Odell", giverAv: { skin: 3, hair: 5, shirt: 6, pants: 3, hat: "none", glasses: "square" } },
  { id: "q-menagerie", name: "The Wandering Menagerie", color: "#7fc24a", icon: "🎪", retired: true,
    house: { id: "house-menagerie", name: "Pip's Big Tent", tx: 46, ty: 20, deco: "house2" },
    giverName: "Ringmaster Pip", giverAv: { skin: 4, hair: 6, shirt: 0, pants: 0, hat: "flower", glasses: "round" } },
  { id: "q-frostfable", name: "The Frostpeak Fable", color: "#7fc4e0", icon: "📖", retired: true,
    house: { id: "house-fable", name: "Vela's Story-Lodge", tx: 12, ty: 6, deco: "house1" },
    giverName: "Storyteller Vela", giverAv: { skin: 2, hair: 3, shirt: 4, pants: 1, hat: "beanie", glasses: "round" } },
  { id: "q-deepecho", name: "The Deep Echo", color: "#a678c9", icon: "🔊", retired: true,
    house: { id: "house-echo", name: "Bram's Listening Post", tx: 68, ty: 38, deco: "house2" },
    giverName: "Echo-listener Bram", giverAv: { skin: 4, hair: 2, shirt: 7, pants: 2, hat: "cap", glasses: "none" } },
  { id: "q-riftwalker", name: "The Riftwalker's Trail", color: "#5b6ee0", icon: "✦", retired: true,
    house: { id: "house-riftcamp", name: "Sable's Riftcamp", tx: 30, ty: 28, deco: "house2" },
    giverName: "Riftwalker Sable", giverAv: { skin: 1, hair: 7, shirt: 0, pants: 0, hat: "none", glasses: "shades" } },
  { id: "q-marshlight", name: "The Marshlight Masquerade", color: "#6f9a4a", icon: "🎭", retired: true,
    house: { id: "house-mask", name: "The Mask-maker's Shack", tx: 38, ty: 45, deco: "house1" },
    giverName: "Mask-maker Wren-Ellis", giverAv: { skin: 3, hair: 6, shirt: 6, pants: 0, hat: "flower", glasses: "none" } },
  { id: "q-scales", name: "The Scales of Aequor", color: "#c9a227", icon: "⚖️", retired: true,
    house: { id: "house-balance", name: "The Balance House", tx: 22, ty: 36, deco: "house1" },
    giverName: "Keeper Aequa", giverAv: { skin: 2, hair: 1, shirt: 4, pants: 1, hat: "none", glasses: "round" } },

  // ===================== NUMBERS: ALGEBRA & DIVISION ====================
  {
    id: "q-missingweights", name: "The Missing Weights", color: "#4fa36a", icon: "⚖️",
    house: { id: "house-market", name: "Pell's Market Stall", tx: 23, ty: 12, deco: "house1" },
    giverName: "Grocer Pell", giverAv: { skin: 2, hair: 4, shirt: 2, pants: 1, hat: "cap", glasses: "none" },
    intro: "Someone has been at my market scales! Every weight used to have its number stamped on it, and now half of them just say x. I can't sell a single apple until I know what they weigh. Help me work out the missing numbers. It's easier than it looks, I promise: an equation is only a sentence with a hole in it.",
    steps: [
      { kind: "lesson", algebra: "one-step",
        giverLine: "Here's the whole secret. Look at what was done to x, then do the opposite to both sides. If something was added, take it away. If x was multiplied, divide. Watch me do one.",
        text: "Learn to solve a one-step equation with Grocer Pell." },
      { kind: "fillstep", algebra: "one-step", blanks: 1,
        giverLine: "Your turn. I've left a gap in my working. Fill it in, and remember: do the opposite.",
        text: "Fill in the missing move of a one-step solution." },
      { kind: "talk", npc: "npc-baker", npcName: "Baker Tilly", teach: "one-step",
        line: "Inverse operations! That's just baker's talk. If I add 5 eggs to a bowl and want to know how many were in it before, I take the 5 away again. Plus undoes minus. Times undoes divide. Every recipe can be run backwards.",
        line2: "And always check: put your answer back into the equation. If the sentence comes out true, you're right.",
        text: "Baker Tilly can run any recipe backwards. Go and ask her how." },
      { kind: "drill", algebra: "one-step", count: 8,
        giverLine: "Eight weights to relabel. Undo, then check. Off you go!",
        text: "Relabel 8 weights: solve 8 one-step equations." },
      { kind: "item", item: "lost-weight", itemName: "Lost Weight", emoji: "⚖️", count: 4, zone: "meadow",
        text: "Find 4 Lost Weights that rolled off into the meadow." },
      { kind: "talk", npc: "npc-mayor", npcName: "Mayor Pom", teach: "eq-story",
        line: "Story problems are just equations wearing a coat. Whatever you don't know becomes x. 'Some' or 'a number' means x. 'More' or 'gained' means add. 'Each' or 'groups of' means multiply. 'Shared' or 'split' means divide.",
        line2: "Read it twice: once for the story, once for the numbers. Then write the equation and solve it.",
        text: "Mayor Pom turns town gossip into equations. Go and listen." },
      { kind: "lesson", algebra: "eq-story",
        giverLine: "The Mayor's right. Turn the words into an equation first. After that, it's the same undoing you already know.",
        text: "Learn to turn a story into an equation with Grocer Pell." },
      { kind: "drill", algebra: "eq-story", count: 6,
        giverLine: "My customers all talk in stories. Six of them are waiting. Write each as an equation, then solve it.",
        text: "Help 6 customers: solve 6 story problems." },
      { kind: "catch", creature: "clovern", zone: "meadow", challenge: { algebra: "one-step" },
        text: "A Clovern is sitting on the heaviest weight. It only answers one-step equations. Befriend it." },
      { kind: "goto", loc: "loc-lilyscale", locName: "the Lily Scale", tx: 19, ty: 17, zone: "meadow",
        text: "Carry the weights to the Lily Scale (now on your map)." },
      { kind: "boss", creature: "equilibrog", loc: "loc-lilyscale", tx: 19, ty: 17, zone: "meadow",
        text: "Equilibrog hops onto the Lily Scale! Solve its equations and story problems to befriend it." },
    ],
    reward: { xp: 700, orbs: { meadow: 5, prism: 2 } },
    outro: "Every weight has its number back, and the Equilibrog sits on the Lily Scale, perfectly level, looking very pleased with itself. \"You didn't guess a single one,\" Pell says. \"You undid them. That's the trick for life, that is.\"",
  },
  {
    id: "q-sharingfeast", name: "The Sharing Feast", color: "#d98a3a", icon: "🍯",
    house: { id: "house-feast", name: "Bramble Hall", tx: 9, ty: 30, deco: "house2" },
    giverName: "Cook Hazel", giverAv: { skin: 4, hair: 3, shirt: 6, pants: 2, hat: "none", glasses: "round" },
    intro: "Every autumn the whole forest comes to Bramble Hall for the Sharing Feast, and the guest of honour is the Divvybear. It won't eat unless every guest has exactly the same amount. This year I've lost my sharing charts! Help me divide everything fairly, and the Divvybear might just choose you.",
    steps: [
      { kind: "talk", npc: "npc-ranger", npcName: "Ranger Fenn", teach: "div-facts",
        line: "Division is sharing fairly, or asking 'how many groups?' 24 ÷ 6 asks: how many 6s make 24? Count by sixes: 6, 12, 18, 24. That's four sixes, so the answer is 4.",
        line2: "And if you know your times tables, you already know your division. They're the same facts, run backwards.",
        text: "Ranger Fenn counts acorns for the squirrels. Ask how he shares them." },
      { kind: "lesson", algebra: "div-facts",
        giverLine: "Every division has a times-table fact hiding inside it. Find the multiplication and you've found the answer.",
        text: "Learn division facts with Cook Hazel." },
      { kind: "drill", algebra: "div-facts", count: 10,
        giverLine: "Ten quick ones while the soup simmers!",
        text: "Solve 10 division facts." },
      { kind: "item", item: "feast-basket", itemName: "Feast Basket", emoji: "🧺", count: 5, zone: "forest",
        text: "Gather 5 Feast Baskets left around the Whispering Woods." },
      { kind: "talk", npc: "npc-baker", npcName: "Baker Tilly", teach: "div-story",
        line: "Feeding a crowd? I do it every morning. The total goes first, then the number of guests. Total ÷ guests = each one's share.",
        line2: "Not sure? Multiply back. Share × guests should give you the total again.",
        text: "Baker Tilly feeds the whole village. Ask how she splits a batch." },
      { kind: "lesson", algebra: "div-story",
        giverLine: "Sharing problems are division problems wearing aprons. Find the total, find how many are sharing, and divide.",
        text: "Learn to solve sharing problems with Cook Hazel." },
      { kind: "fillstep", algebra: "div-story", blanks: 1,
        giverLine: "Finish my working for me. How much does each guest get?",
        text: "Finish the working of a sharing problem." },
      { kind: "drill", algebra: "div-story", count: 6,
        giverLine: "Six tables to set. Share everything out fairly!",
        text: "Set 6 tables: solve 6 sharing problems." },
      { kind: "catch", creature: "barkun", zone: "forest", challenge: { algebra: "div-facts" },
        text: "A Barkun has been hoarding the feast nuts. It only answers division facts. Befriend it." },
      { kind: "drill", algebra: ["div-facts", "div-story"], count: 6,
        giverLine: "One last check before the guest of honour arrives: a mix of both kinds.",
        text: "Final check: solve 6 mixed division problems." },
      { kind: "goto", loc: "loc-feasttable", locName: "the Feast Table", tx: 3, ty: 34, zone: "forest",
        text: "Carry the baskets to the Feast Table (now on your map)." },
      { kind: "boss", creature: "divvybear", loc: "loc-feasttable", tx: 3, ty: 34, zone: "forest",
        text: "The Divvybear lumbers out to inspect the shares! Solve its division problems to befriend it." },
    ],
    reward: { xp: 750, orbs: { forest: 6, prism: 2 } },
    outro: "Not one guest has a crumb more than another, and the Divvybear sets down its paw with a satisfied grunt. \"A fair feast,\" Cook Hazel beams. \"And a fair cook to thank for it. You.\"",
  },
  {
    id: "q-deepledger", name: "The Deep Ledger", color: "#7a6fc0", icon: "🧮",
    house: { id: "house-assay", name: "Ondine's Assay Office", tx: 69, ty: 31, deco: "house1" },
    giverName: "Assayer Ondine", giverAv: { skin: 1, hair: 6, shirt: 7, pants: 3, hat: "cap", glasses: "square" },
    intro: "The Gleamcave miners bring me great heaps of ore, and I must divide every heap fairly into carts. Big numbers, too big for times tables alone! There's a way to do it one digit at a time, called long division. Learn it with me, and you may meet the Quotaur who keeps the Deep Ledger.",
    steps: [
      { kind: "lesson", algebra: "long-division",
        giverLine: "Big numbers don't frighten an assayer. You split them one digit at a time, left to right, writing each answer on top of the bracket. Watch closely.",
        text: "Learn long division with Assayer Ondine." },
      { kind: "talk", npc: "npc-miner", npcName: "Miner Quill", teach: "long-division",
        line: "Here's how we remember the order down the mine: Dad, Mom, Sister, Brother. Divide, Multiply, Subtract, Bring down. Then if there's another digit left, round you go again!",
        line2: "If your subtraction ever leaves a number as big as the one you're dividing by, your guess was too small. Try one more.",
        text: "Miner Quill has a rhyme for long division. Go and learn it." },
      { kind: "fillstep", algebra: "long-division", blanks: 2,
        giverLine: "Here's a half-finished ledger. Dad, Mom, Sister, Brother. Fill in the gaps.",
        text: "Fill in 2 missing numbers of a long division." },
      { kind: "drill", algebra: "long-division", count: 4,
        giverLine: "Four heaps of ore. Divide each one into carts.",
        text: "Divide 4 ore heaps: solve 4 long divisions." },
      { kind: "talk", npc: "npc-trader", npcName: "Trader Vish",
        line: "Never trust an answer you haven't checked! Multiply your answer by the number you divided by. If you get back the big number, it's right. If not, look for the step that went wrong. I check every bill that way, twice.",
        text: "Trader Vish never accepts a total without checking it. Ask how." },
      { kind: "fillstep", algebra: "long-division", blanks: 3,
        giverLine: "A harder page of the ledger. Three gaps this time. Check it by multiplying when you're done!",
        text: "Fill in 3 missing numbers of a long division." },
      { kind: "item", item: "ore-tally", itemName: "Ore Tally", emoji: "🪨", count: 4, zone: "cavern",
        text: "Collect 4 Ore Tallies glinting in the Gleamcave." },
      { kind: "drill", algebra: "long-division", count: 4,
        giverLine: "Four more heaps, and then you're ready for the Ledger.",
        text: "Divide 4 more heaps: solve 4 long divisions." },
      { kind: "catch", creature: "crystile", zone: "cavern", challenge: { algebra: "long-division" },
        text: "A Crystile is guarding a heap of crystals. Divide them fairly to befriend it." },
      { kind: "goto", loc: "loc-deepledger", locName: "the Deep Ledger", tx: 65, ty: 38, zone: "cavern",
        text: "Bring the tallies to the Deep Ledger in the cavern (now on your map)." },
      { kind: "boss", creature: "quotaur", loc: "loc-deepledger", tx: 65, ty: 38, zone: "cavern",
        text: "The Quotaur stamps out of the dark! Work its long divisions to befriend it." },
    ],
    reward: { xp: 800, orbs: { cavern: 6, prism: 2 } },
    outro: "The Quotaur checks your last answer by multiplying it back, nods its great horned head, and writes your name in the Deep Ledger. \"Dad, Mom, Sister, Brother,\" Ondine laughs. \"You'll never forget it now.\"",
  },
  {
    id: "q-halvarr", name: "The Halvarr of Lake Lumen", color: "#3d8fc0", icon: "🎣",
    house: { id: "house-lockhouse", name: "The Lockkeeper's House", tx: 15, ty: 45, deco: "house2" },
    giverName: "Lockkeeper Rowan", giverAv: { skin: 3, hair: 1, shirt: 5, pants: 0, hat: "beanie", glasses: "none" },
    intro: "There's a fish in Lake Lumen called the Halvarr, with a seam right down its middle. The old anglers say you can only land one if you can think backwards: undo what was added, then multiply back what was divided. I've been fishing for it for forty years. Shall we try together?",
    steps: [
      { kind: "talk", npc: "npc-angler", npcName: "Angler Moss",
        line: "x ÷ 4 = 6? Think of it like this: I split my catch into 4 equal baskets and each basket had 6 fish. So the whole catch was 4 × 6 = 24. Multiplying undoes dividing!",
        text: "Angler Moss knows how to undo a division. Go and ask." },
      { kind: "lesson", algebra: "div-equation",
        giverLine: "Now something has been added or taken away after the dividing. Undo in reverse order: first undo the + or −, then multiply to undo the ÷. Watch.",
        text: "Learn to solve equations with division with Lockkeeper Rowan." },
      { kind: "fillstep", algebra: "div-equation", blanks: 2,
        giverLine: "Your turn. Two gaps. Undo the adding first, then the dividing.",
        text: "Fill in the missing steps of a division equation." },
      { kind: "drill", algebra: "div-equation", count: 6,
        giverLine: "Six practice casts. Reverse order, every time.",
        text: "Practice: solve 6 division equations." },
      { kind: "talk", npc: "npc-weigher", npcName: "Weigh-master Ballas", teach: "two-step",
        line: "It's the same rule as every two-step equation. Undo the last thing first, like taking off your boots before your socks.",
        text: "Weigh-master Ballas says this is an old trick in disguise. Find out why." },
      { kind: "item", item: "tide-mark", itemName: "Tide Mark", emoji: "🌊", count: 3, zone: "lake",
        text: "Find 3 Tide Marks along the shores of Lake Lumen." },
      { kind: "catch", creature: "shellby", zone: "lake", challenge: { algebra: "div-equation" },
        text: "A Shellby is hiding the bait. Solve its division equations to befriend it." },
      { kind: "drill", algebra: ["div-equation", "two-step", "one-step"], count: 8,
        giverLine: "A mixed bag, so you're ready for anything. Look at each one and choose the right undo.",
        text: "Mixed practice: solve 8 equations of different kinds." },
      { kind: "goto", loc: "loc-splitpool", locName: "the Split Pool", tx: 27, ty: 30, zone: "lake",
        text: "Head to the Split Pool on Lake Lumen (now on your map)." },
      { kind: "boss", creature: "halvarr", loc: "loc-splitpool", tx: 27, ty: 30, zone: "lake",
        text: "The Halvarr surfaces! Solve its equations to befriend it." },
    ],
    reward: { xp: 750, orbs: { lake: 6, prism: 2 } },
    outro: "The Halvarr glides into your arms as gently as a leaf. Rowan wipes away a tear. \"Forty years,\" he says. \"And all I needed was someone who could think backwards.\"",
  },
  {
    id: "q-owlexam", name: "The Owl's Examination", color: "#6c56a8", icon: "🦉",
    house: { id: "house-exam", name: "The Examination Hall", tx: 54, ty: 4, deco: "house1" },
    giverName: "Proctor Elba", giverAv: { skin: 0, hair: 2, shirt: 4, pants: 1, hat: "none", glasses: "round" },
    intro: "The Sapientowl sets the hardest examination in the world. It never asks the same kind of question twice in a row, so memorising won't help: you have to understand. Sit my five practice papers, and when you're ready, climb to the Owl's Crag. I'll be cheering for you.",
    steps: [
      { kind: "talk", npc: "npc-scribe", npcName: "Scribe Tessel",
        line: "The Owl tests whether you can tell problems apart. Before you solve anything, ask: what has been done to the unknown? Then undo it, last thing first. And if it's a sharing problem, it's division.",
        text: "Scribe Tessel once passed the Owl's examination. Ask for advice." },
      { kind: "drill", algebra: ["one-step", "two-step"], count: 6,
        giverLine: "Paper One: equations. Some take one step, some take two.",
        text: "Paper I: solve 6 equations." },
      { kind: "drill", algebra: ["div-facts", "div-story"], count: 6,
        giverLine: "Paper Two: division facts and sharing problems.",
        text: "Paper II: solve 6 division problems." },
      { kind: "fillstep", algebra: "long-division", blanks: 2,
        giverLine: "Paper Three, part one: finish this long division. Dad, Mom, Sister, Brother!",
        text: "Paper III: finish a long division." },
      { kind: "drill", algebra: "long-division", count: 3,
        giverLine: "Paper Three, part two: three long divisions of your own.",
        text: "Paper III: solve 3 long divisions." },
      { kind: "drill", algebra: ["eq-story", "div-story"], count: 5,
        giverLine: "Paper Four: story problems. Read each one twice.",
        text: "Paper IV: solve 5 story problems." },
      { kind: "drill", algebra: "div-equation", count: 5,
        giverLine: "Paper Five: equations with division. Reverse order!",
        text: "Paper V: solve 5 division equations." },
      { kind: "item", item: "exam-seal", itemName: "Exam Seal", emoji: "🔏", count: 3, zone: "ridge",
        text: "Collect 3 Exam Seals on Ember Ridge to prove you passed." },
      { kind: "catch", creature: "boulderox", zone: "ridge", challenge: { algebra: ["two-step", "div-equation"] },
        text: "A Boulderox blocks the path to the crag. Solve its equations to befriend it." },
      { kind: "talk", npc: "npc-scout", npcName: "Scout Bly",
        line: "The Owl's on the high crag. Word is it never asks the same kind of question twice in a row. Stay calm, read every one, and show your thinking.",
        text: "Scout Bly has seen the Owl's Crag. Ask about the way up." },
      { kind: "goto", loc: "loc-owlcrag", locName: "the Owl's Crag", tx: 60, ty: 8, zone: "ridge",
        text: "Climb to the Owl's Crag (now on your map)." },
      { kind: "boss", creature: "sapientowl", loc: "loc-owlcrag", tx: 60, ty: 8, zone: "ridge",
        text: "The Sapientowl opens one eye. Pass its mixed examination to befriend it." },
    ],
    reward: { xp: 900, orbs: { ridge: 6, prism: 3 } },
    outro: "The Sapientowl hoots once, which Proctor Elba says is the highest mark it has ever given. \"You didn't just know the answers,\" she says. \"You knew which question you were being asked. That's the whole of mathematics, really.\"",
  },

  // ===================== WORDS: THE SPELLING BEE LIST ===================
  {
    id: "q-humminghive", name: "The Humming Hive", color: "#e0a21a", icon: "🐝",
    house: { id: "house-apiary", name: "Beatrix's Apiary", tx: 44, ty: 15, deco: "house2" },
    giverName: "Beekeeper Beatrix", giverAv: { skin: 1, hair: 3, shirt: 6, pants: 0, hat: "flower", glasses: "none" },
    intro: "My bees keep a letter in every honeycomb cell, and together the cells spell the Hive Words. Last night a storm shook the comb and the letters fell everywhere! Only someone who knows the words by heart can put them back. Will you learn them with me? Then the Melliqueen herself might come out to thank you.",
    steps: [
      { kind: "spellbee", pool: [0, 0.25], mode: "copy", count: 15,
        giverLine: "First, meet the words. Look at each one, say it out loud, then copy it carefully.",
        text: "Meet the Hive Words: copy 15 of them." },
      { kind: "talk", npc: "npc-scribe", npcName: "Scribe Tessel",
        line: "Here's how scribes learn a word. Look at it. Say it slowly. Cover it up. Write it from memory. Then check it, letter by letter. Look, say, cover, write, check!",
        text: "Scribe Tessel has a trick for remembering spellings. Go and learn it." },
      { kind: "spellbee", pool: [0, 0.25], mode: "flash", count: 15,
        giverLine: "Now from memory. I'll show you each word for a moment, then hide it. Look, say, cover, write!",
        text: "Spell 15 Hive Words from memory." },
      { kind: "item", item: "honey-drop", itemName: "Honey Drop", emoji: "🍯", count: 4, zone: "meadow",
        text: "Gather 4 Honey Drops in the meadow for the hungry bees." },
      { kind: "spellbee", pool: [0, 0.25], mode: "gaps", count: 15,
        giverLine: "The rain washed some letters out of the comb. Spell each whole word again.",
        text: "Fill the washed-out gaps: spell 15 Hive Words." },
      { kind: "catch", creature: "zumble", zone: "meadow", challenge: "bee", pool: [0, 0.25],
        text: "A Zumble is buzzing the Hive Words. Spell them to befriend it." },
      { kind: "spellbee", pool: [0, 0.25], mode: "scramble", count: 15,
        giverLine: "The wind jumbled the letters! Put each word back in the right order.",
        text: "Unscramble 15 Hive Words." },
      { kind: "spellbee", pool: [0, 0.25], mode: "mix", count: 15,
        giverLine: "A final review: any style, any word, fifteen in all. You've got this.",
        text: "Hive review: spell 15 words in any style." },
      { kind: "goto", loc: "loc-queenscomb", locName: "the Queen's Comb", tx: 48, ty: 37, zone: "meadow",
        text: "Carry the honey to the Queen's Comb (now on your map)." },
      { kind: "boss", creature: "melliqueen", loc: "loc-queenscomb", tx: 48, ty: 37, zone: "meadow",
        text: "The Melliqueen emerges! Spell the Hive Words to befriend her." },
    ],
    reward: { xp: 700, orbs: { meadow: 6, prism: 2 } },
    outro: "Every cell is back in place and the whole hive hums the words in tune. The Melliqueen settles on your shoulder. \"She's chosen you,\" Beatrix whispers. \"She only does that for the very best spellers.\"",
  },
  {
    id: "q-whisperinglibrary", name: "The Whispering Library", color: "#4f8a5b", icon: "📚",
    house: { id: "house-library", name: "The Whispering Library", tx: 2, ty: 10, deco: "house1" },
    giverName: "Librarian Sorrel", giverAv: { skin: 3, hair: 5, shirt: 2, pants: 1, hat: "none", glasses: "round" },
    intro: "Shh! Something has been nibbling the books in my library. Words are going missing from the pages, and the Tomewyrm in the Deep Stacks is getting restless. If you can learn these words well enough to write them back in, it might just let you borrow it.",
    steps: [
      { kind: "spellbee", pool: [0.25, 0.5], mode: "copy", count: 15,
        giverLine: "Start by copying each word neatly into my catalogue. Say it as you write it.",
        text: "Copy 15 Library Words into the catalogue." },
      { kind: "spellbee", pool: [0.25, 0.5], mode: "flash", count: 15,
        giverLine: "Now the real test. I'll show each word, then close the book.",
        text: "Spell 15 Library Words from memory." },
      { kind: "talk", npc: "npc-ranger", npcName: "Ranger Fenn",
        line: "A tricky word? Break it into chunks, the way you'd cross a stream on stepping stones. Say each chunk as you write it, and the whole word falls into place.",
        text: "Ranger Fenn crosses streams on stepping stones. Ask what that has to do with spelling." },
      { kind: "spellbee", pool: [0.25, 0.5], mode: "gaps", count: 15,
        giverLine: "These pages were nibbled. Spell each whole word, chunk by chunk.",
        text: "Mend the nibbled pages: spell 15 Library Words." },
      { kind: "item", item: "lost-page", itemName: "Lost Page", emoji: "📄", count: 4, zone: "forest",
        text: "Find 4 Lost Pages blowing around the Whispering Woods." },
      { kind: "catch", creature: "glimmoth", zone: "forest", challenge: "bee", pool: [0.25, 0.5],
        text: "A Glimmoth has been eating the words! Spell them to befriend it." },
      { kind: "spellbee", pool: [0.25, 0.5], mode: "scramble", count: 15,
        giverLine: "The pages are back, but the letters are all mixed up. Put them right.",
        text: "Unscramble 15 Library Words." },
      { kind: "spellbee", pool: [0.25, 0.5], mode: "flash", count: 15,
        giverLine: "One more reading from memory: fifteen of them, and see if you can get every one on the first try.",
        text: "Second reading: spell 15 Library Words from memory again." },
      { kind: "spellbee", pool: [0.25, 0.5], mode: "mix", count: 15,
        giverLine: "Last review before the Deep Stacks: fifteen words, any style.",
        text: "Library review: spell 15 words in any style." },
      { kind: "goto", loc: "loc-deepstacks", locName: "the Deep Stacks", tx: 11, ty: 16, zone: "forest",
        text: "Return the pages to the Deep Stacks (now on your map)." },
      { kind: "boss", creature: "tomewyrm", loc: "loc-deepstacks", tx: 11, ty: 16, zone: "forest",
        text: "The Tomewyrm uncoils from the shelves! Spell the Library Words to befriend it." },
    ],
    reward: { xp: 750, orbs: { forest: 6, prism: 2 } },
    outro: "Every word is back on its page. The Tomewyrm peers at you over its reading glasses, then curls up at your feet. \"Well,\" says Sorrel, \"I suppose it's checked out to you now. Please return it in good condition.\"",
  },
  {
    id: "q-lettersonthewind", name: "Letters on the Wind", color: "#5fa8de", icon: "🪁",
    house: { id: "house-kite", name: "Juno's Kite Hut", tx: 15, ty: 2, deco: "house2" },
    giverName: "Kitewright Juno", giverAv: { skin: 0, hair: 7, shirt: 1, pants: 2, hat: "beanie", glasses: "none" },
    intro: "My kites write words across the sky over Frostpeak. But the north wind keeps scrambling the letters, and the Glyphawk that rides it only lands for someone who can put them right. Learn my sky words and we'll fly the biggest kite of all.",
    steps: [
      { kind: "spellbee", pool: [0.5, 0.75], mode: "copy", count: 15,
        giverLine: "Copy each sky word onto a kite tail. Neat letters fly better!",
        text: "Copy 15 Sky Words onto kite tails." },
      { kind: "talk", npc: "npc-icewright", npcName: "Icewright Thora",
        line: "Say the word out loud and listen for every sound. Each sound needs letters to show it. Then watch for the silent letters that sneak in. Those are the ones that trip people up.",
        text: "Icewright Thora carves words in ice. Ask how she gets them right." },
      { kind: "spellbee", pool: [0.5, 0.75], mode: "scramble", count: 15,
        giverLine: "Here comes the north wind! Unscramble each word before it blows away.",
        text: "Unscramble 15 Sky Words." },
      { kind: "spellbee", pool: [0.5, 0.75], mode: "flash", count: 15,
        giverLine: "A word flashes across the sky, then it's gone. Catch it from memory!",
        text: "Spell 15 Sky Words from memory." },
      { kind: "item", item: "kite-tail", itemName: "Kite Tail", emoji: "🎏", count: 4, zone: "tundra",
        text: "Find 4 Kite Tails blown across Frostpeak." },
      { kind: "catch", creature: "snowlet", zone: "tundra", challenge: "bee", pool: [0.5, 0.75],
        text: "A Snowlet is rolling around in the fallen letters. Spell the Sky Words to befriend it." },
      { kind: "spellbee", pool: [0.5, 0.75], mode: "gaps", count: 15,
        giverLine: "Frost has covered some letters. Spell each whole word.",
        text: "Clear the frost: spell 15 Sky Words." },
      { kind: "spellbee", pool: [0.5, 0.75], mode: "scramble", count: 15,
        giverLine: "The wind's picking up again! Fifteen jumbled words. Quick!",
        text: "Storm review: unscramble 15 Sky Words." },
      { kind: "goto", loc: "loc-windwardpeak", locName: "Windward Peak", tx: 26, ty: 9, zone: "tundra",
        text: "Fly the great kite from Windward Peak (now on your map)." },
      { kind: "boss", creature: "glyphawk", loc: "loc-windwardpeak", tx: 26, ty: 9, zone: "tundra",
        text: "The Glyphawk dives out of the clouds! Spell the Sky Words to befriend it." },
    ],
    reward: { xp: 750, orbs: { tundra: 6, prism: 2 } },
    outro: "The Glyphawk lands on the great kite's frame and writes your name across the sky in frost. Juno cheers so loudly that half of Frostpeak comes out to look.",
  },
  {
    id: "q-tidescript", name: "The Tide Script", color: "#2c4a8a", icon: "🖋️",
    house: { id: "house-scriptorium", name: "Mira's Scriptorium", tx: 56, ty: 10, deco: "house1" },
    giverName: "Inkmaker Mira", giverAv: { skin: 4, hair: 0, shirt: 0, pants: 3, hat: "none", glasses: "square" },
    intro: "I make my ink from the shells the Scriptide leaves on the shore of Lake Lumen. Every tide it writes words in the sand, and every wave washes letters away. If you can learn the Tide Words well enough to fill in what the waves took, the Scriptide will trust you.",
    steps: [
      { kind: "spellbee", pool: [0.75, 1], mode: "copy", count: 15,
        giverLine: "Copy each Tide Word in your best handwriting. Ink is precious, so take care!",
        text: "Copy 15 Tide Words." },
      { kind: "spellbee", pool: [0.75, 1], mode: "gaps", count: 15,
        giverLine: "Here's what the tide left behind. Spell each whole word.",
        text: "Fill in what the waves washed away: spell 15 Tide Words." },
      { kind: "talk", npc: "npc-trader", npcName: "Trader Vish",
        line: "I write every price tag twice: once quickly, once checking every letter. Mistakes like to hide in the middle of words, not at the ends. Always check the middle!",
        text: "Trader Vish never misspells a price tag. Ask how." },
      { kind: "spellbee", pool: [0.75, 1], mode: "flash", count: 15,
        giverLine: "The tide comes in fast. See each word, then write it before the wave!",
        text: "Spell 15 Tide Words from memory." },
      { kind: "item", item: "ink-shell", itemName: "Ink Shell", emoji: "🐚", count: 4, zone: "lake",
        text: "Gather 4 Ink Shells on the shores of Lake Lumen." },
      { kind: "catch", creature: "scarabright", zone: "desert", challenge: "bee", pool: [0.75, 1],
        text: "A Scarabright is rolling ink across the dunes. Spell the Tide Words to befriend it." },
      { kind: "spellbee", pool: [0.75, 1], mode: "scramble", count: 15,
        giverLine: "A big wave mixed up all the letters. Put them back in order.",
        text: "Unscramble 15 Tide Words." },
      { kind: "spellbee", pool: [0.75, 1], mode: "mix", count: 15,
        giverLine: "Final review: fifteen words, any style. Check the middles!",
        text: "Tide review: spell 15 words in any style." },
      { kind: "goto", loc: "loc-inkshore", locName: "the Ink Shore", tx: 24, ty: 19, zone: "lake",
        text: "Take the shells to the Ink Shore on Lake Lumen (now on your map)." },
      { kind: "boss", creature: "scriptide", loc: "loc-inkshore", tx: 24, ty: 19, zone: "lake",
        text: "The Scriptide glides into the shallows! Spell the Tide Words to befriend it." },
    ],
    reward: { xp: 750, orbs: { lake: 4, desert: 3, prism: 2 } },
    outro: "The Scriptide writes one last word in the sand, and this time the wave doesn't wash it away. It's your name. Mira fills a bottle with the darkest, shiniest ink you've ever seen. \"For your own writing,\" she says.",
  },
  {
    id: "q-grandbee", name: "The Grand Spelling Bee", color: "#c0398a", icon: "🏆",
    house: { id: "house-beehall", name: "Willowmere Bee Hall", tx: 39, ty: 35, deco: "house1" },
    giverName: "Judge Marigold", giverAv: { skin: 2, hair: 6, shirt: 4, pants: 0, hat: "flower", glasses: "round" },
    intro: "Welcome to the Grand Spelling Bee of Willowmere! Every word on the Bee List could come up, so this is best tried after the Hive, the Library, the Kites and the Tide Script. Win, and the Lexicorn will appear on the village green. It has never come out for anyone who hasn't practised.",
    steps: [
      { kind: "spellbee", pool: [0, 1], mode: "flash", count: 15,
        giverLine: "Qualifying round! Fifteen words from anywhere on the list, from memory.",
        text: "Qualifying round: spell 15 words from memory." },
      { kind: "talk", npc: "npc-mayor", npcName: "Mayor Pom",
        line: "Nervous? Everyone is! Take a breath, picture the word written down, and spell it in your head before you write it. Then check the middle, like Trader Vish says.",
        text: "Mayor Pom has judged a hundred Bees. Ask for advice." },
      { kind: "spellbee", pool: [0, 1], mode: "gaps", count: 15,
        giverLine: "Round two: fifteen words with missing letters. Spell every one in full.",
        text: "Round two: spell 15 words with missing letters." },
      { kind: "catch", creature: "chirpit", zone: "meadow", challenge: "bee", pool: [0, 1],
        text: "A Chirpit is singing Bee words. Spell them to befriend it." },
      { kind: "spellbee", pool: [0, 1], mode: "scramble", count: 15,
        giverLine: "Round three: fifteen scrambled words. Unjumble them!",
        text: "Round three: unscramble 15 words." },
      { kind: "catch", creature: "finling", zone: "lake", challenge: "bee", pool: [0, 1],
        text: "A Finling is splashing Bee words across the lake. Spell them to befriend it." },
      { kind: "spellbee", pool: [0, 1], mode: "flash", count: 15,
        giverLine: "The Championship Round. Fifteen words from anywhere on the Bee List, from memory, and they'll be ones you haven't had yet in this Bee.",
        text: "Championship round: spell 15 words from memory." },
      { kind: "item", item: "bee-medal", itemName: "Bee Medal", emoji: "🏅", count: 3, zone: "meadow",
        text: "Collect 3 Bee Medals scattered around Willowmere." },
      { kind: "goto", loc: "loc-villagegreen", locName: "the Village Green", tx: 16, ty: 39, zone: "meadow",
        text: "Go to the Village Green for the final ceremony (now on your map)." },
      { kind: "boss", creature: "lexicorn", loc: "loc-villagegreen", tx: 16, ty: 39, zone: "meadow",
        text: "The Lexicorn steps onto the green! Spell any word on the Bee List to befriend it." },
    ],
    reward: { xp: 1200, orbs: { meadow: 6, prism: 5 } },
    outro: "The Lexicorn lowers its lettered horn to you, and all of Willowmere bursts into applause. Judge Marigold hangs a golden medal round your neck. \"Champion of the Grand Spelling Bee,\" she announces. \"Every word, spelled true.\"",
  },
];

window.QUEST_BY_ID = {};
window.QUESTS.forEach(function (q) { window.QUEST_BY_ID[q.id] = q; });
